### ISSUE TITLE
mvn package fails on downloading parallel_FFTj

### ISSUE THREAD

**Issue by tlambert03** [MicronOxford/SIMcheck#29]
when compiling  with `mvn package` I'm getting an error when it reaches the parallel_fftj dependency.

it appears that the FFTj URL at the maven repo is broken: https://repo.maven.apache.org/maven2/edu/emory/mathcs/parallel_fftj/1.4/parallel_fftj-1.4.jar

I was able to build it by manually downloading parallel_FFTj at https://sites.google.com/site/piotrwendykier/software/parallelfftj and then adding the following code to the corresponding dependency in pom.xml:

`<scope>system</scope>`
`<systemPath>${project.basedir}/lib/parallel_fftj-1.4.jar</systemPath>`

but addressing the dependency in pom.xml would be helpful

**Comment by carandraug** [comment]
Do you know of a maven repository that has the parallel fftj? As far we know, it is only available for manual download.

However, we have since found that Parallel FFTJ is not free software due to it's dependency on parallel colt (which is dependent on an old, GPL incompatible, version of AIDA). We are trying to sort it out.

**Comment by tlambert03** [comment]
I understand.  No i don't know of another maven repo for parallel fftj.  I guess I just assumed since there was a pointer in the pom.xml that it might have worked at one point in the past... so just figured I'd point it out.  Not a big deal at all.  thanks!
